name: Release 🚀

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  statuses: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: pnpm/action-setup@v3
        with:
          version: 9.14.4
      - name: Use Node.js 20.18.1
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"
          cache: "pnpm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            npm-deps-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sudo apt-get install libsecret-1-dev
          sudo apt-get install gnome-keyring
          pnpm install
          pnpm run release
